# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task -l
    silent: true
  
  setup-conda-env:
    desc: setup python conda enviroment
    cmds:
      - conda create -n djfedos-bootstrap-env python=3.8 -y

  go:
    desc: 
    cmds:
    - conda activate djfedos-bootstrap-env    

  test:
    desc: run a simple test on main.py
    cmds:
      - task test-hello
      - task test-reverser
      - echo "=== ALL TESTS PASS ==="

  test-hello:
    desc: run a simple test on main.py
    cmds:
      - python main.py world | grep "Hello"
      
  test-reverser:
    desc: run a simple test on reverser.py
    cmds:
      - python reverser.py ABC | grep "CBA"
      - echo "{{.TASK}} are PASSED"
      
  test-flipper-ui:
    desc: image flip test
    cmds:
      - python flipper.py Remap_Tutorial_Original_Image.jpg

  test-flipper-save:
    desc: image flip save test
    cmds:
      - python flipper.py Remap_Tutorial_Original_Image.jpg --save_path __out/out.jpg
      - |-
        if [[ "$(du -sh __out/out.jpg | cut -d' ' -f1  )" == "0"  ]]; then
          echo "Empty file"
          exit 1
        fi