# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  setup-conda-env:
    desc: setup python conda enviroment
    cmds:
      - conda create -n djfedos-bootstrap-env python=3.8 -y

