# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task -l
    silent: true
  
  setup-conda-env:
    desc: setup python conda enviroment
    cmds:
      - conda create -n djfedos-bootstrap-env python=3.8 -y

  test:
    desc: run a simple test on main.py
    cmds:
      - python main.py

  test-hello:
    desc: run a simple test on main.py
    cmds:
      - python main.py | grep "Hello"      