# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task -l
    silent: true
  
  setup-conda-env:
    desc: setup python conda enviroment
    cmds:
      - conda create -n djfedos-bootstrap-env python=3.8 -y

  test:
    desc: run a simple test on main.py
    cmds:
      - task test-hello
      - task test-reverser
      - echo "=== ALL TESTS PASS ==="

  test-hello:
    desc: run a simple test on main.py
    cmds:
      - python main.py world | grep "Hello"
      
  test-reverser:
    desc: run a simple test on reverser.py
    cmds:
      - python reverser.py ABC | grep "CBA"
      - echo "{{.TASK}} are PASSED"       